CB-1- Explanation
Codubee/RecipeMakerTTH11-1 pull request #1
Opened 2020-11-08 14:02 UTC by alekhyapinnamaneni

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
This PR creates a new feature. It adds a Jumbotron component that explains what this project does/how to use it.

* **What is the current behavior? What does the code do before you made the new changes?** 
Before I made the new changes, the code generates a blank page.

* **What is the new behavior?**
After the changes I have made, the code generates a page titled "Recipe Maker" along with an explanation of what the Recipe Maker does.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No.

* **Other information**:
n/a

2020-11-11 21:43 UTC, sunghyun96 reviewed
Looks good Alekhya! The only thing I can think of is maybe adding some styling to the component later on to blend the design with the other components once we get a better idea of how some of these other components will look.

2020-11-12 21:52 UTC, sunghyun96 approved these changes
I am going to go ahead and give an approval to accompany my comment I made yesterday, since the present code works and any style changes can be made during later sprints if necessary!

2020-11-12 22:01 UTC, AdemOdza approved these changes
Looks good! I agree with Sung, styling could be added later on when we figure out what we want our style to be.

2020-11-15 05:37 UTC, Codubee requested changes
Great work Alekhya! Left one comment that we can discuss. It also looks like there are some merge conflicts that I can help you resolve if youd like.

2020-11-15 05:37 UTC, Codubee commented on frontend/src/components/LandingPage/Explanation/Explanation.js
> +const Explanation = (props) =>
Can we change this into a functional component instead of a const here.

2020-11-17 22:04 UTC, Stacey-Masi approved these changes
Nice job finding the color scheme and implementing it. Making the title bold or white might look good as well, but this is great!

2020-11-23 03:15 UTC, Codubee approved these changes

2020-11-23 03:15 UTC, merged